server:
  port: "8081"

database:
  host: "localhost"
  port: 5433
  user: "postgres"
  password: "postgres"
  name: "tennis_diary"
  sslMode: "disable"
  timeZone: "Asia/Shanghai"

# database:
#   host: "tennisdaily-postgres"
#   port: 5432
#   user: "postgres"
#   password: "postgres"
#   name: "tennis_diary"
#   sslMode: "disable"
#   timeZone: "Asia/Shanghai"

jwt:
  secret: "dev-secret-change-me"
  expireHours: 720

wechat:
  appId: ""
  appSecret: ""