server:
  port: "8081"

# database:
#   # host: "localhost"
#   # port: 3306
#   #   user: "root"
#   # password: "root"
#   host: "sh-cynosdbmysql-grp-4686fcoi.sql.tencentcdb.com"
#   port: 26404
#   user: "root"
#   password: "MFAcn5Fy"
#   name: "tennis_diary"
#   charset: "utf8mb4"
#   parseTime: true
#   loc: "Asia/Shanghai"
#   timeZone: "Asia/Shanghai"


database:
  host: "10.26.103.99"
  port: 3306
  user: "root"
  password: "MFAcn5Fy"
  name: "tennis_diary"
  charset: "utf8mb4"
  parseTime: true
  loc: "Asia/Shanghai"
  timeZone: "Asia/Shanghai"

  
jwt:
  secret: "dev-secret-change-me"
  expireHours: 720

wechat:
  appId: ""
  appSecret: ""



sessionEnums:
  categories:
    - value: 1
      label: 日常球局
      subCategories:
        - value: 1
          label: 打单
        - value: 2
          label: 双打
    - value: 2
      label: 训练
      subCategories:
        - value: 21
          label: 发球
        - value: 22
          label: 截击
        - value: 23
          label: 正手
        - value: 24
          label: 反手
        - value: 25
          label: 体能      
        - value: 26
          label: 力量
        - value: 27
          label: 高压
        - value: 28
          label: 综合 
        - value: 29
          label: 其他
    - value: 3
      label: 比赛
      subCategories:
        - value: 1
          label: 单打
        - value: 2
          label: 双打