DELETE FROM racket_library;

ALTER TABLE racket_library
  ADD COLUMN brand_id BIGINT NOT NULL DEFAULT 0 COMMENT '品牌ID' AFTER id,
  ADD COLUMN series_id BIGINT NOT NULL DEFAULT 0 COMMENT '系列ID' AFTER brand,
  ADD COLUMN series VARCHAR(100) NOT NULL DEFAULT '' COMMENT '系列' AFTER series_id;
